#!/usr/bin/env bash
# Script to config domain zone to point to load balancer

display_info() {
    local domain=$1
    local subdomain=$2
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk -v sub="$subdomain" '{print "The subdomain " sub " is a " $4 " record and points to " $5}'
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
else
    display_info "$domain" "$subdomain"
fi
